keys:
  - &uses:
    - &zenoix age1zr38fq23gs0u8x8uq2c9umvjsh7cqmg379rlmxt0qqgnexglg39sj8wg79
  - &hosts:
    - &walnut-laptop age1z2lgeq00h44yqe3muk9tx58s3f040yven2jhn3kgy3rflfeqpgaq3dqdte
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *zenoix
          - *walnut-laptop
