{
  imports = [
    ./anki.nix
    ./coding.nix
    ./docker.nix
    ./firefox.nix
    ./keymapp.nix
    ./kitty.nix
    ./libreoffice.nix
    ./mullvad.nix
    ./neovim.nix
    ./obsidian.nix
    ./qbittorrent.nix
    ./shell-config.nix
    ./signal.nix
    ./steam.nix
    ./stylix.nix
    ./thunar.nix
    ./tor-browser.nix
    ./vesktop.nix
    ./vlc.nix
  ];
}
