{
  imports = [
    ./alpha.nix
    ./bigfile.nix
    ./biscuits.nix
    ./completion.nix
    ./conform-nvim.nix
    ./dadbod.nix
    ./dressing.nix
    ./fugitive.nix
    ./gitgutter.nix
    ./harpoon.nix
    ./illuminate.nix
    ./indent-blankline.nix
    ./iron.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./mini.nix
    ./neogen.nix
    ./notify.nix
    ./nvim-ts-context-commentstring.nix
    ./oil.nix
    ./render-markdown.nix
    ./screenkey.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./todo-comments.nix
    ./treesitter-context.nix
    ./treesitter.nix
    ./trouble.nix
    ./undotree.nix
    ./web-devicons.nix
  ];
}
