{
  imports = [
    ./aerial.nix
    ./alpha.nix
    ./bigfile.nix
    ./biscuits.nix
    ./blink-cmp.nix
    ./conform-nvim.nix
    ./dadbod.nix
    ./fzf-lua.nix
    ./gitgutter.nix
    ./harpoon.nix
    ./indent-blankline.nix
    ./iron.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./mini.nix
    ./neogen.nix
    ./nvim-ts-context-commentstring.nix
    ./oil.nix
    ./render-markdown.nix
    ./screenkey.nix
    ./snacks.nix
    ./tiny-inline-diagnostic.nix
    ./tmux-navigator.nix
    ./todo-comments.nix
    ./treesitter-context.nix
    ./treesitter-textobjects.nix
    ./treesitter.nix
    ./trouble.nix
    ./undotree.nix
  ];
}
